### ISSUE TITLE
should empty list of toggle states be allowed?

### ISSUE THREAD

**Issue by dbaron** [tabatkins/css-toggle#19]
The [syntax of `<toggle-specifier>`](https://tabatkins.github.io/css-toggle/#typedef-toggle-specifier) currently says:

> [`<toggle-states>`](https://tabatkins.github.io/css-toggle/#typedef-toggle-states) = [`<integer [1,∞]>`](https://drafts.csswg.org/css-values-4/#integer-value) [|](https://drafts.csswg.org/css-values-4/#comb-one) '[' [`<custom-ident>`](https://drafts.csswg.org/css-values-4/#identifier-value)[*](https://drafts.csswg.org/css-values-4/#mult-zero-plus) ']'

This allows an empty list of custom identifiers.  I suspect this is not desirable.  To parallel the `<integer>` value being required to be at least one, it seems like the list of custom identifiers should be required to have length at least one, and the `*` should instead be a `+`.

**Comment by tabatkins** [comment]
Hm actually it should be at least two. The integer is at least one, specifying 1 *active* state, which pairs with the single inactive state.
