### ISSUE TITLE
Should "activator" / activate be more integrated here?

### ISSUE THREAD

**Issue by bkardell** [tabatkins/css-toggle#2]
In reviewing this I had a lot of trouble wrapping my head around things because we use the word 'toggle' a bunch and it can mean a few things (and I think here, does)... it's both a noun, and a verb (as is 'set') and it appears on both sides... I spent a bunch of time drawing pictures and making notes trying to wrap my head around things and name/describe them with explcit names that make sense to me.  In my head, 'toggle' the data/counter is manipulated/triggered by an 'activator' which might or might not be on the same element.  I noticed that the draft uses activate all over, and example 5 even says "and declares itself a toggle activator".  Currently this is wrapped up in shorthand, but what is the longhand property that would declare something a toggle activator? I guess it is 'toggle-set', which sounds like a group of toggles.  Just dropping the thought that maybe there is something to using 'activate' or something here?

**Comment by tabatkins** [comment]
I only use the noun "toggle" to mean one thing - the state held by an element (tho it does show up in a lot of noun phrases related to the toggle)

`toggle-set` is the property that makes something an activator. `toggle` is the shorthand for both `toggle-create` and `toggle-set`. In both cases the last word is meant as a verb, which *is* pretty unique in CSS; bikeshedding welcome, but it's important to me that it convey some sense of temporality.

`toggle-activate` isn't a bad idea, indeed.

**Comment by tabatkins** [comment]
I've switched the names around a bit; they're now `toggle-root` and `toggle-trigger`, which hopefully avoids noun/verb confusion like "set".

**Comment by bkardell** [comment]
it definitely does for me fwiw
