### ISSUE TITLE
value matching should be described in terms of a toggle and a value

### ISSUE THREAD

**Issue by dbaron** [tabatkins/css-toggle#22]
The definition of [value matching](https://tabatkins.github.io/css-toggle/#toggle-match-value) is currently described in terms of two values.  However, it uses a list of states, so I think it should really be described in terms of one toggle (whose list of states and value are used) and one other value.  I think this is currently somewhat implicit in both of the two references to the concept, but it would probably be better to be more explicit.

**Comment by tabatkins** [comment]
Ah yup, ended up doing this already. "Match values" now takes a toggle and a value, and optionally a list of states to override the toggle's states with.
