### ISSUE TITLE
Element.toggles should be readonly and [SameObject]

### ISSUE THREAD

**Issue by dbaron** [tabatkins/css-toggle#26]
I think [`Element.toggles`](https://tabatkins.github.io/css-toggle/#dom-element-toggles) should probably be both `readonly` and `[SameObject]`.  At least, that's my understanding of what it's intended to do.

If that's incorrect, then the spec should probably define how its setter works and define when the object changes.

**Comment by tabatkins** [comment]
Ah yeah it def should be, thanks.
