### ISSUE TITLE
CSSToggleEvent constructor and init dict are wrong in IDL

### ISSUE THREAD

**Issue by dbaron** [tabatkins/css-toggle#29]
The CSSToggleEvent constructor is broken in two ways:

First, if I create an idlharness test that uses the IDL from the css-toggle spec, I get:

```
3	FAIL idl_test validation Validation error at line 43 in css-toggle, inside `interface CSSToggleEvent -> constructor -> argument eventInitDict`:
4	  constructor(CSSToggleEventInit eventInitDict);
5	                                 ^ Dictionary argument must be optional if it has no required fields
```

so I think the event init argument should be optional.

Second, I'm not aware of any other event constructors omitting the type of the event as the first argument (always `DOMString type`).

(I'm planning to fix the IDL that I commit to WPT and to Chromium on the basis of this comment.)

**Comment by tabatkins** [comment]
Yes, it should def be optional. That's my bad.

> Second, I'm not aware of any other event constructors omitting the type of the event as the first argument 

Hm, I guess usually a specific event class is reused for several related things that all want to expose the same data, so they take it to let you generate each type. I wasn't immediately planning on doing so for this, but I suppose it's a reasonable extension point, so sure. I'll have to figure out some names.

Looking at a few specs, it's not clear what the constructor does with the argument - does it just pass it thru regardless of its value? I don't see anything in DOM or other specs defining event subclasses that validates the value.

**Comment by dbaron** [comment]
I thought the name was [already defined](https://tabatkins.github.io/css-toggle/#fire-a-toggle-change-event) as `togglechange`.

**Comment by tabatkins** [comment]
Right, but if I'm only doing the one type of event, letting the name be settable in the constructor args wasn't necessary.

(But yeah I might do more in the future, so I'll add it.)

**Comment by dbaron** [comment]
Oh, and on an extremely similar topic:

`CSSToggleEventInit` should derive from `EventInit`, like every other event's init dict.
