### ISSUE TITLE
Is example 8 missing the toggle name?

### ISSUE THREAD

**Issue by bkardell** [tabatkins/css-toggle#3]
Currently example 8  has...

```
.tristate-check {
  toggle: check 0/2;
}
.tristate-check:checked(1) {
  /* "checked" styles */
}
.tristate-check:checked(2) {
  /* "indeterminate" styles */
}
```

But doesn't it need to specify the specific name of the toggle it is checking?  I feel like this creates a further unfortunate reuse of the same words in too many contexts, but I believe it should be

```
.tristate-check {
  toggle: check 0/2;
}
.tristate-check:checked(check 1) {
  /* "checked" styles */
}
.tristate-check:checked(check 2) {
  /* "indeterminate" styles */
}
```

(not a real suggestion) but it would be funny if these attached an ::after that was ' Sibilance. Sibilance.' (https://www.youtube.com/watch?v=EPVL45WkH84 if you don't get the old SNL ref)

**Comment by tabatkins** [comment]
Yes it is.
