### ISSUE TITLE
why are toggles an event target?

### ISSUE THREAD

**Issue by dbaron** [tabatkins/css-toggle#32]
The [formal definition](https://tabatkins.github.io/css-toggle/#fire-a-toggle-change-event) of a toggle change event says that they're fired at elements.  I think this probably makes sense since it's possible to get the toggle from the element, but a little weirder to get the element from the toggle.  It's also a little simpler, since there's no new event target.

However, `CSSToggle` derives from `EventTarget`, which made me think that togglechange events were meant to be fired at the toggles rather than the elements.

**Comment by tabatkins** [comment]
Hm, looks like no particular reason. I must have just anticipated firing the events and so added it on, and not realized when I actually went to write the text that the logical event target was the element instead. Removed.
