### ISSUE TITLE
CSSToggleEventInit should inherit from EventInit

### ISSUE THREAD

**Issue by dbaron** [tabatkins/css-toggle#34]
As I mentioned in #29 (morphing the issue right before you fixed it), `CSSToggleEventInit` should inherit from `EventInit`, like all the other init dicts for events.

**Comment by tabatkins** [comment]
Yeah, I spotted the comment and fixed it just before I left today. 😃

**Comment by dbaron** [comment]
Yeah, ok... I see it in the repository, but the spec on github.io hasn't updated yet, for some reason.
