### ISSUE TITLE
states setter steps should also check length of list

### ISSUE THREAD

**Issue by dbaron** [tabatkins/css-toggle#37]
The [states setter steps](https://tabatkins.github.io/css-toggle/#dom-csstogglevalue-states) should be updated to match the equivalent edits to the constructor in cbe62536bf6e133cf24128f6c4149c25197d194e, and throw a `SyntaxError` exception when the list has length < 2.

**Comment by tabatkins** [comment]
Argh, right. I've synced the language more closely as well.
