### ISSUE TITLE
Toggle specifier error in spec

### ISSUE THREAD

**Issue by bkardell** [tabatkins/css-toggle#8]
https://tabatkins.github.io/css-toggle/#typedef-toggle-specifier  should say that if a single numeric argument is provided it is the max state. As it is currently it would imply that most of these examples won't work as they seem to be setting the default state and implying that the max is also the default (thus kind of a no-op)

**Comment by tabatkins** [comment]
Fixed at some point in the past; it's now clearer that the first (initial value) number is optional, and the second (max value) is required.
